/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPortalRouteImport } from './routes/api/portal'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as AuthenticatedWhoViewedMeRouteImport } from './routes/_authenticated/who-viewed-me'
import { Route as AuthenticatedWavesRouteImport } from './routes/_authenticated/waves'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPhotosRouteImport } from './routes/_authenticated/photos'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNearbyRouteImport } from './routes/_authenticated/nearby'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedLookingNowRouteImport } from './routes/_authenticated/looking-now'
import { Route as AuthenticatedInterestsRouteImport } from './routes/_authenticated/interests'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedAppealRouteImport } from './routes/_authenticated/appeal'
import { Route as AuthenticatedAlbumRouteImport } from './routes/_authenticated/album'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiWebhookPolarRouteImport } from './routes/api/webhook/polar'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedUserUserIdRouteImport } from './routes/_authenticated/user.$userId'
import { Route as AuthenticatedAdminVenuesRouteImport } from './routes/_authenticated/admin/venues'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminRulesRouteImport } from './routes/_authenticated/admin/rules'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminMessageReportsRouteImport } from './routes/_authenticated/admin/message-reports'
import { Route as AuthenticatedAdminAppealsRouteImport } from './routes/_authenticated/admin/appeals'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalRoute = ApiPortalRouteImport.update({
  id: '/api/portal',
  path: '/api/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhoViewedMeRoute =
  AuthenticatedWhoViewedMeRouteImport.update({
    id: '/who-viewed-me',
    path: '/who-viewed-me',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWavesRoute = AuthenticatedWavesRouteImport.update({
  id: '/waves',
  path: '/waves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPhotosRoute = AuthenticatedPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNearbyRoute = AuthenticatedNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLookingNowRoute = AuthenticatedLookingNowRouteImport.update({
  id: '/looking-now',
  path: '/looking-now',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterestsRoute = AuthenticatedInterestsRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppealRoute = AuthenticatedAppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlbumRoute = AuthenticatedAlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiWebhookPolarRoute = ApiWebhookPolarRouteImport.update({
  id: '/api/webhook/polar',
  path: '/api/webhook/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserUserIdRoute = AuthenticatedUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminVenuesRoute =
  AuthenticatedAdminVenuesRouteImport.update({
    id: '/venues',
    path: '/venues',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRulesRoute = AuthenticatedAdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessageReportsRoute =
  AuthenticatedAdminMessageReportsRouteImport.update({
    id: '/message-reports',
    path: '/message-reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAppealsRoute =
  AuthenticatedAdminAppealsRouteImport.update({
    id: '/appeals',
    path: '/appeals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dev': typeof DevRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/album': typeof AuthenticatedAlbumRoute
  '/appeal': typeof AuthenticatedAppealRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/interests': typeof AuthenticatedInterestsRoute
  '/looking-now': typeof AuthenticatedLookingNowRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/waves': typeof AuthenticatedWavesRoute
  '/who-viewed-me': typeof AuthenticatedWhoViewedMeRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal': typeof ApiPortalRoute
  '/admin/appeals': typeof AuthenticatedAdminAppealsRoute
  '/admin/message-reports': typeof AuthenticatedAdminMessageReportsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/venues': typeof AuthenticatedAdminVenuesRoute
  '/user/$userId': typeof AuthenticatedUserUserIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dev': typeof DevRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/album': typeof AuthenticatedAlbumRoute
  '/appeal': typeof AuthenticatedAppealRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/interests': typeof AuthenticatedInterestsRoute
  '/looking-now': typeof AuthenticatedLookingNowRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/photos': typeof AuthenticatedPhotosRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/waves': typeof AuthenticatedWavesRoute
  '/who-viewed-me': typeof AuthenticatedWhoViewedMeRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal': typeof ApiPortalRoute
  '/admin/appeals': typeof AuthenticatedAdminAppealsRoute
  '/admin/message-reports': typeof AuthenticatedAdminMessageReportsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/venues': typeof AuthenticatedAdminVenuesRoute
  '/user/$userId': typeof AuthenticatedUserUserIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/dev': typeof DevRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/album': typeof AuthenticatedAlbumRoute
  '/_authenticated/appeal': typeof AuthenticatedAppealRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/interests': typeof AuthenticatedInterestsRoute
  '/_authenticated/looking-now': typeof AuthenticatedLookingNowRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/nearby': typeof AuthenticatedNearbyRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/photos': typeof AuthenticatedPhotosRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/waves': typeof AuthenticatedWavesRoute
  '/_authenticated/who-viewed-me': typeof AuthenticatedWhoViewedMeRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal': typeof ApiPortalRoute
  '/_authenticated/admin/appeals': typeof AuthenticatedAdminAppealsRoute
  '/_authenticated/admin/message-reports': typeof AuthenticatedAdminMessageReportsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/venues': typeof AuthenticatedAdminVenuesRoute
  '/_authenticated/user/$userId': typeof AuthenticatedUserUserIdRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dev'
    | '/legal'
    | '/login'
    | '/admin'
    | '/album'
    | '/appeal'
    | '/community'
    | '/interests'
    | '/looking-now'
    | '/messages'
    | '/nearby'
    | '/onboarding'
    | '/photos'
    | '/profile'
    | '/referrals'
    | '/settings'
    | '/waves'
    | '/who-viewed-me'
    | '/api/checkout'
    | '/api/portal'
    | '/admin/appeals'
    | '/admin/message-reports'
    | '/admin/reports'
    | '/admin/rules'
    | '/admin/users'
    | '/admin/venues'
    | '/user/$userId'
    | '/api/auth/callback'
    | '/api/webhook/polar'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dev'
    | '/legal'
    | '/login'
    | '/album'
    | '/appeal'
    | '/community'
    | '/interests'
    | '/looking-now'
    | '/messages'
    | '/nearby'
    | '/onboarding'
    | '/photos'
    | '/profile'
    | '/referrals'
    | '/settings'
    | '/waves'
    | '/who-viewed-me'
    | '/api/checkout'
    | '/api/portal'
    | '/admin/appeals'
    | '/admin/message-reports'
    | '/admin/reports'
    | '/admin/rules'
    | '/admin/users'
    | '/admin/venues'
    | '/user/$userId'
    | '/api/auth/callback'
    | '/api/webhook/polar'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/dev'
    | '/legal'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/album'
    | '/_authenticated/appeal'
    | '/_authenticated/community'
    | '/_authenticated/interests'
    | '/_authenticated/looking-now'
    | '/_authenticated/messages'
    | '/_authenticated/nearby'
    | '/_authenticated/onboarding'
    | '/_authenticated/photos'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/settings'
    | '/_authenticated/waves'
    | '/_authenticated/who-viewed-me'
    | '/api/checkout'
    | '/api/portal'
    | '/_authenticated/admin/appeals'
    | '/_authenticated/admin/message-reports'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/rules'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/venues'
    | '/_authenticated/user/$userId'
    | '/api/auth/callback'
    | '/api/webhook/polar'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  DevRoute: typeof DevRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiPortalRoute: typeof ApiPortalRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiWebhookPolarRoute: typeof ApiWebhookPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal': {
      id: '/api/portal'
      path: '/api/portal'
      fullPath: '/api/portal'
      preLoaderRoute: typeof ApiPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/who-viewed-me': {
      id: '/_authenticated/who-viewed-me'
      path: '/who-viewed-me'
      fullPath: '/who-viewed-me'
      preLoaderRoute: typeof AuthenticatedWhoViewedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/waves': {
      id: '/_authenticated/waves'
      path: '/waves'
      fullPath: '/waves'
      preLoaderRoute: typeof AuthenticatedWavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/photos': {
      id: '/_authenticated/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof AuthenticatedPhotosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nearby': {
      id: '/_authenticated/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AuthenticatedNearbyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/looking-now': {
      id: '/_authenticated/looking-now'
      path: '/looking-now'
      fullPath: '/looking-now'
      preLoaderRoute: typeof AuthenticatedLookingNowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interests': {
      id: '/_authenticated/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof AuthenticatedInterestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appeal': {
      id: '/_authenticated/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AuthenticatedAppealRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/album': {
      id: '/_authenticated/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AuthenticatedAlbumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/webhook/polar': {
      id: '/api/webhook/polar'
      path: '/api/webhook/polar'
      fullPath: '/api/webhook/polar'
      preLoaderRoute: typeof ApiWebhookPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/user/$userId': {
      id: '/_authenticated/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof AuthenticatedUserUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/venues': {
      id: '/_authenticated/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AuthenticatedAdminVenuesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rules': {
      id: '/_authenticated/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AuthenticatedAdminRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/message-reports': {
      id: '/_authenticated/admin/message-reports'
      path: '/message-reports'
      fullPath: '/admin/message-reports'
      preLoaderRoute: typeof AuthenticatedAdminMessageReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appeals': {
      id: '/_authenticated/admin/appeals'
      path: '/appeals'
      fullPath: '/admin/appeals'
      preLoaderRoute: typeof AuthenticatedAdminAppealsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAppealsRoute: typeof AuthenticatedAdminAppealsRoute
  AuthenticatedAdminMessageReportsRoute: typeof AuthenticatedAdminMessageReportsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRulesRoute: typeof AuthenticatedAdminRulesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVenuesRoute: typeof AuthenticatedAdminVenuesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAppealsRoute: AuthenticatedAdminAppealsRoute,
  AuthenticatedAdminMessageReportsRoute: AuthenticatedAdminMessageReportsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRulesRoute: AuthenticatedAdminRulesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVenuesRoute: AuthenticatedAdminVenuesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAlbumRoute: typeof AuthenticatedAlbumRoute
  AuthenticatedAppealRoute: typeof AuthenticatedAppealRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedInterestsRoute: typeof AuthenticatedInterestsRoute
  AuthenticatedLookingNowRoute: typeof AuthenticatedLookingNowRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNearbyRoute: typeof AuthenticatedNearbyRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPhotosRoute: typeof AuthenticatedPhotosRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWavesRoute: typeof AuthenticatedWavesRoute
  AuthenticatedWhoViewedMeRoute: typeof AuthenticatedWhoViewedMeRoute
  AuthenticatedUserUserIdRoute: typeof AuthenticatedUserUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAlbumRoute: AuthenticatedAlbumRoute,
  AuthenticatedAppealRoute: AuthenticatedAppealRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedInterestsRoute: AuthenticatedInterestsRoute,
  AuthenticatedLookingNowRoute: AuthenticatedLookingNowRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNearbyRoute: AuthenticatedNearbyRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPhotosRoute: AuthenticatedPhotosRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWavesRoute: AuthenticatedWavesRoute,
  AuthenticatedWhoViewedMeRoute: AuthenticatedWhoViewedMeRoute,
  AuthenticatedUserUserIdRoute: AuthenticatedUserUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  DevRoute: DevRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiPortalRoute: ApiPortalRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiWebhookPolarRoute: ApiWebhookPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
