/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevRouteImport } from './routes/dev'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPortalRouteImport } from './routes/api/portal'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as AuthenticatedWhoViewedMeRouteImport } from './routes/_authenticated/who-viewed-me'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAlbumRouteImport } from './routes/_authenticated/album'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiWebhookPolarRouteImport } from './routes/api/webhook/polar'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalRoute = ApiPortalRouteImport.update({
  id: '/api/portal',
  path: '/api/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhoViewedMeRoute =
  AuthenticatedWhoViewedMeRouteImport.update({
    id: '/who-viewed-me',
    path: '/who-viewed-me',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlbumRoute = AuthenticatedAlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiWebhookPolarRoute = ApiWebhookPolarRouteImport.update({
  id: '/api/webhook/polar',
  path: '/api/webhook/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dev': typeof DevRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/album': typeof AuthenticatedAlbumRoute
  '/home': typeof AuthenticatedHomeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/who-viewed-me': typeof AuthenticatedWhoViewedMeRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal': typeof ApiPortalRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/dev': typeof DevRoute
  '/login': typeof LoginRoute
  '/album': typeof AuthenticatedAlbumRoute
  '/home': typeof AuthenticatedHomeRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/who-viewed-me': typeof AuthenticatedWhoViewedMeRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal': typeof ApiPortalRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/dev': typeof DevRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/album': typeof AuthenticatedAlbumRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/who-viewed-me': typeof AuthenticatedWhoViewedMeRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/portal': typeof ApiPortalRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/webhook/polar': typeof ApiWebhookPolarRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/dev'
    | '/login'
    | '/admin'
    | '/album'
    | '/home'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/referrals'
    | '/settings'
    | '/who-viewed-me'
    | '/api/checkout'
    | '/api/portal'
    | '/admin/reports'
    | '/admin/users'
    | '/api/auth/callback'
    | '/api/webhook/polar'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/dev'
    | '/login'
    | '/album'
    | '/home'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/referrals'
    | '/settings'
    | '/who-viewed-me'
    | '/api/checkout'
    | '/api/portal'
    | '/admin/reports'
    | '/admin/users'
    | '/api/auth/callback'
    | '/api/webhook/polar'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/callback'
    | '/dev'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/album'
    | '/_authenticated/home'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/settings'
    | '/_authenticated/who-viewed-me'
    | '/api/checkout'
    | '/api/portal'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/users'
    | '/api/auth/callback'
    | '/api/webhook/polar'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  DevRoute: typeof DevRoute
  LoginRoute: typeof LoginRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiPortalRoute: typeof ApiPortalRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiWebhookPolarRoute: typeof ApiWebhookPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal': {
      id: '/api/portal'
      path: '/api/portal'
      fullPath: '/api/portal'
      preLoaderRoute: typeof ApiPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/who-viewed-me': {
      id: '/_authenticated/who-viewed-me'
      path: '/who-viewed-me'
      fullPath: '/who-viewed-me'
      preLoaderRoute: typeof AuthenticatedWhoViewedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/album': {
      id: '/_authenticated/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AuthenticatedAlbumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/webhook/polar': {
      id: '/api/webhook/polar'
      path: '/api/webhook/polar'
      fullPath: '/api/webhook/polar'
      preLoaderRoute: typeof ApiWebhookPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAlbumRoute: typeof AuthenticatedAlbumRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWhoViewedMeRoute: typeof AuthenticatedWhoViewedMeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAlbumRoute: AuthenticatedAlbumRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWhoViewedMeRoute: AuthenticatedWhoViewedMeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
  DevRoute: DevRoute,
  LoginRoute: LoginRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiPortalRoute: ApiPortalRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiWebhookPolarRoute: ApiWebhookPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
